<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>InternshipJournal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\InternshipJournal.Domain\InternshipJournal.Domain.csproj" />
    <ProjectReference Include="..\InternshipJournal.TestBase\InternshipJournal.TestBase.csproj" />
  </ItemGroup>

</Project>
